import type {Metadata} from "next";
import "./globals.css";
import Layout from "@/app/(client)/layout";
import {ReactNode} from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {

    return (
        <html lang="en">
        <head>
            <link
                href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css"
                rel="stylesheet"
            />
        </head>
        <body className={`antialiased font-[Arial]`}>
            <div className="@apply font-[Arial] bg-[linear-gradient(135deg,black,#737373)] min-h-screen max-h-screen overflow-auto [scrollbar-width: none]">
                {children}
            </div>
        </body>
        </html>
);
}
